apiVersion: v1
kind: PersistentVolume
metadata:
  name: hdlee-sonarqube-pv
  labels:
    type: sonarqube
spec:
  storageClassName: sonarqube
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /opt/sonarqube

